### PR TITLE
[Wildcard Matching] fix

### PR DESCRIPTION
**Pull request by jakwings**
add one test case: `isMatch("*", "*a")`

### CODE REVIEW

**Comment by haoel** [comment]
I think you probably misunderstood the problem.

For this problem, it needs to check a wildcard pattern whether matches a string,  not another wildcard pattern. 

Particularly, with regarding to the function prototype -`isMatch(s, p)` , the argument `s` represents a string(not a pattern),  the `p` represents a wildcard pattern(also includes the case which without any wildcard chars)

So, in your case, you try to match two patterns `("*", "*a")`, it is out of the scope of this problem.

**Comment by jakwings** [comment]
No, I know `s` is not a pattern. The test case is not for what you means.

**Comment by jakwings** [comment]
Sorry, I made a wrong test case…The test case should be like this:

```cpp
isMatch("**a", "*a")
```

**Comment by haoel** [comment]
After read your code, I understand what your PR wants to do. - make the code easier to read. 

Thanks for that, but next time please write a meaningful title and much more clear description of your PR. 

This PR is really confused !

**Comment by jakwings** [comment]
Sorry for such confusion. Please let me make a new pull request later. ;-)

**Pull request closed without merging**
