### PR TITLE
The ac solution using Java for problem for 19、24、61、82、83、86、143、203、234

### PR DESCRIPTION
**Pull request by kosoraYintai**
Hello!
I have finished the ac code using Java for 
problem 19 ( https://leetcode.com/problems/remove-nth-node-from-end-of-list/description/ ),
problem 24 ( https://leetcode.com/problems/swap-nodes-in-pairs/description/ ),
problem 61 ( https://leetcode.com/problems/rotate-list/description/ ),
problem 82 ( https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/description/ ),
problem 83 ( https://leetcode.com/problems/remove-duplicates-from-sorted-list/description/ ),
problem 86 ( https://leetcode.com/problems/partition-list/description/ ),
problem 143 ( https://leetcode.com/problems/reorder-list/description/ ),
problem 203 ( https://leetcode.com/problems/remove-linked-list-elements/description/ ),
problem 234 ( https://leetcode.com/problems/palindrome-linked-list/description/ ),
I also wrote some assistant comments as the idea of solving the problem in code.
Those problems above  all belong to Linked-List-Topic.

### CODE REVIEW

**Comment by kosoraYintai** [comment]
Hello, could you please merge this commit in spare time?

**Comment by haoel** [comment]
Sorry fo late, and this PR has some conflicts, so, could you please verify it?

**Comment by kosoraYintai** [comment]
OK, but it‘s very strange because github said "This branch has no conflicts with the base branch", what should I do? Close this PR and re pull code form base to my fork?

**Comment by haoel** [comment]
yes, please try it.

**Comment by kosoraYintai** [comment]
How to cancel this PR? I tried close it and pull from your project as head fork to my project as base fork, but github still said "There isn’t anything to compare."

**Comment by kosoraYintai** [comment]
Hello, I have reverted Readme.md, and the last files are all new. Please try whether you can merge this PR or not. If success, I will re modify Readme.md and commit.

**Pull request closed without merging**
